### ISSUE TITLE
Refetch the events when something is updated

### ISSUE THREAD

**Issue by Joao208** [typper-io/calendar-ai#2]

**Comment by Jott4** [comment]
I'll work on this

**Comment by Joao208** [comment]
@Jott4 Do you have an estimate for when this feature will be ready for deployment?

**Comment by Jott4** [comment]
I've started to work on this, have a problem to render the events on the calendar, but i fixed. Hope i can finish on this week

**Comment by Joao208** [comment]
This commit has closed this issue https://github.com/typper-io/calendar-ai/commit/cbe20ce94df0eb78b4e4b710b5df1f2a8fa65f4a
